### ISSUE TITLE
get_usgs_stations() is broken in 0.3.2

### ISSUE THREAD

**Issue by pmav99** [conda-forge/searvey-feedstock#7]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The `get_usgs_stations()` function throws an error in 0.3.2:
```
python -c 'import searvey.usgs; searvey.usgs.get_usgs_stations()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/panos/miniconda/envs/removeme/lib/python3.10/site-packages/searvey/usgs.py", line 209, in get_usgs_stations
    usgs_stations = _get_all_usgs_stations()
  File "/home/panos/miniconda/envs/removeme/lib/python3.10/site-packages/searvey/usgs.py", line 153, in _get_all_usgs_stations
    func_kwargs=[
  File "/home/panos/miniconda/envs/removeme/lib/python3.10/site-packages/searvey/usgs.py", line 156, in <listcomp>
    "output": set(j for i in _get_usgs_output_codes().values() for j in i),
  File "/home/panos/miniconda/envs/removeme/lib/python3.10/site-packages/searvey/usgs.py", line 101, in _get_usgs_output_codes
    df_param_info = _get_usgs_output_info()
  File "/home/panos/miniconda/envs/removeme/lib/python3.10/site-packages/searvey/usgs.py", line 89, in _get_usgs_output_info
    df_param_cd, _ = nwis.get_pmcodes(var)
  File "/home/panos/miniconda/envs/removeme/lib/python3.10/site-packages/dataretrieval/nwis.py", line 459, in get_pmcodes
    return _read_rdb(response.text), _set_metadata(response, **kwargs)
  File "/home/panos/miniconda/envs/removeme/lib/python3.10/site-packages/dataretrieval/nwis.py", line 713, in _read_rdb
    df = pd.read_csv(StringIO(rdb), delimiter='\t', skiprows=count + 2,
  File "/home/panos/miniconda/envs/removeme/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/panos/miniconda/envs/removeme/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/panos/miniconda/envs/removeme/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/panos/miniconda/envs/removeme/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    return parser.read(nrows)
  File "/home/panos/miniconda/envs/removeme/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1778, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File "/home/panos/miniconda/envs/removeme/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 230, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 808, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 866, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 852, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1973, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 362, saw 3
```

### Installed packages

```shell
name: removeme
channels:
  - gbrey
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=2.2.1=pyhd8ed1ab_0
  - attrs=22.2.0=pyh71513ae_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.12.0=pyha770c72_0
  - blosc=1.21.3=hafa529b_0
  - boost-cpp=1.78.0=h75c5d50_1
  - branca=0.6.0=pyhd8ed1ab_0
  - brotli=1.0.9=h166bdaf_8
  - brotli-bin=1.0.9=h166bdaf_8
  - brotlipy=0.7.0=py310h5764c6d_1005
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.12.7=ha878542_0
  - cairo=1.16.0=ha61ee94_1014
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py310h255011f_3
  - cfitsio=4.2.0=hd9d235c_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.0.7=py310hdf3cbec_0
  - cryptography=40.0.1=py310h34c0648_0
  - curl=7.88.1=hdc1c0ab_1
  - cycler=0.11.0=pyhd8ed1ab_0
  - dataretrieval=0.7=pyhd8ed1ab_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - deprecated=1.2.13=pyh6c4a22f_0
  - erddapy=1.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.1.1=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=hcb278e6_1
  - fiona=1.9.2=py310ha325b7b_0
  - folium=0.14.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.39.3=py310h1fa729e_0
  - freetype=2.12.1=hca18f0e_1
  - freexl=1.0.6=h166bdaf_1
  - gdal=3.6.3=py310hbad6b5a_6
  - geopandas=0.12.2=pyhd8ed1ab_0
  - geopandas-base=0.12.2=pyha770c72_0
  - geos=3.11.2=hcb278e6_0
  - geotiff=1.7.1=h480ec47_8
  - gettext=0.21.1=h27087fc_0
  - giflib=5.2.1=h0b41bf4_3
  - hdf4=4.2.15=h501b40f_6
  - hdf5=1.14.0=nompi_hb72d44e_103
  - html5lib=1.1=pyh9f0ad1d_0
  - icu=70.1=h27087fc_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.1.0=pyha770c72_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - ipython=8.12.0=pyh41d4057_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.2.0=pyhd8ed1ab_0
  - json-c=0.16=hc379101_0
  - kealib=1.5.0=he7a6254_1
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py310hbf28c38_1
  - krb5=1.20.1=h81ceb04_0
  - lcms2=2.15=haa2dc70_1
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libaec=1.0.6=hcb278e6_1
  - libblas=3.9.0=16_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_8
  - libbrotlidec=1.0.9=h166bdaf_8
  - libbrotlienc=1.0.9=h166bdaf_8
  - libcblas=3.9.0=16_linux64_openblas
  - libcurl=7.88.1=hdc1c0ab_1
  - libdeflate=1.18=h0b41bf4_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgdal=3.6.3=h73bb59c_6
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libglib=2.74.1=h606061b_1
  - libgomp=12.2.0=h65d4601_19
  - libiconv=1.17=h166bdaf_0
  - libjpeg-turbo=2.1.5.1=h0b41bf4_0
  - libkml=1.3.0=h37653c0_1015
  - liblapack=3.9.0=16_linux64_openblas
  - libnetcdf=4.9.2=nompi_hf3f8848_103
  - libnghttp2=1.52.0=h61bc06f_0
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libpng=1.6.39=h753d276_0
  - libpq=15.2=hb675445_0
  - librttopo=1.1.0=h0d5128d_13
  - libspatialindex=1.9.3=h9c3ff4c_4
  - libspatialite=5.0.1=h7d1ca68_25
  - libsqlite=3.40.0=h753d276_0
  - libssh2=1.10.0=hf14f497_3
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libtiff=4.5.0=ha587672_6
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.0=h0b41bf4_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.10.3=hca2bb57_4
  - libxslt=1.1.37=h873f0b0_0
  - libzip=1.9.2=hc929e4a_1
  - libzlib=1.2.13=h166bdaf_4
  - limits=3.2.0=pyhd8ed1ab_0
  - lxml=4.9.2=py310hbdc0903_0
  - lz4-c=1.9.4=hcb278e6_0
  - mapclassify=2.5.0=pyhd8ed1ab_1
  - markupsafe=2.1.2=py310h1fa729e_0
  - matplotlib-base=3.7.1=py310he60537e_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - munch=2.5.0=py_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.3=h27087fc_1
  - networkx=3.0=pyhd8ed1ab_0
  - nspr=4.35=h27087fc_0
  - nss=3.89=he45b914_0
  - numpy=1.24.2=py310h8deb116_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.1.0=h0b41bf4_0
  - packaging=23.0=pyhd8ed1ab_0
  - pandas=1.5.3=py310h9b08913_1
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre2=10.40=hc3806b6_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.4.0=py310h065c6d2_2
  - pip=23.0.1=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - platformdirs=3.2.0=pyhd8ed1ab_0
  - pluggy=1.0.0=pyhd8ed1ab_5
  - pooch=1.7.0=pyha770c72_3
  - poppler=23.03.0=hf052cbe_1
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=15.2=h3248436_0
  - proj=9.2.0=h8ffa02c_0
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pydantic=1.10.7=py310h1fa729e_0
  - pygments=2.14.0=pyhd8ed1ab_0
  - pyopenssl=23.1.1=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyproj=3.5.0=py310hb814896_1
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest=7.2.2=pyhd8ed1ab_0
  - python=3.10.10=he550d4f_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.10=3_cp310
  - pytz=2023.3=pyhd8ed1ab_0
  - readline=8.2=h8228510_1
  - requests=2.28.2=pyhd8ed1ab_0
  - rtree=1.0.1=py310hbdcdc62_1
  - scikit-learn=1.2.2=py310h41b6a48_1
  - scipy=1.10.1=py310h8deb116_0
  - searvey=0.3.2=pyhd8ed1ab_0
  - setuptools=67.6.1=pyhd8ed1ab_0
  - shapely=2.0.1=py310h056c13c_1
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=h9fff704_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlite=3.40.0=h4ff8645_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tiledb=2.13.2=hd532e3d_0
  - tk=8.6.12=h27826a3_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tqdm=4.65.0=pyhd8ed1ab_1
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.5.0=hd8ed1ab_0
  - typing_extensions=4.5.0=pyha770c72_0
  - tzcode=2023c=h0b41bf4_0
  - tzdata=2023c=h71feb2d_0
  - unicodedata2=15.0.0=py310h5764c6d_0
  - urllib3=1.26.15=pyhd8ed1ab_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - wheel=0.40.0=pyhd8ed1ab_0
  - wrapt=1.15.0=py310h1fa729e_0
  - xarray=2023.3.0=pyhd8ed1ab_0
  - xerces-c=3.2.4=h55805fa_1
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xyzservices=2023.2.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.2=h3eb15da_6
```

### Environment info

```shell
active environment : removeme
    active env location : /home/panos/miniconda/envs/removeme
            shell level : 1
       user config file : /home/panos/.condarc
 populated config files : /home/panos/.condarc
          conda version : 23.1.0
    conda-build version : 3.23.3
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.1=0
                          __glibc=2.37=0
                          __linux=6.2.8=0
                          __unix=0=0
       base environment : /home/panos/miniconda  (writable)
      conda av data dir : /home/panos/miniconda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/gbrey/linux-64
                          https://conda.anaconda.org/gbrey/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/panos/miniconda/pkgs
                          /home/panos/.conda/pkgs
       envs directories : /home/panos/miniconda/envs
                          /home/panos/.conda/envs
               platform : linux-64
             user-agent : conda/23.1.0 requests/2.28.1 CPython/3.10.9 Linux/6.2.8-arch1-1 arch/rolling glibc/2.37
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by pmav99** [comment]
This is a strange error... According to the traceback `dataretrieval` uses pandas to read a CSV that has been downloaded from the USGS website. While parsing the CSV, some line is malformed, i.e. it has additional fields. The question is why does the parser work with the PyPI package?

## PyPI
```
env_name=test_conda_python_and_pypi_searvey
mamba create -n "${env_name}" python=3.10 -y 
conda activate "${env_name}"
which python3  
python3 -V
python3 -mpip install searvey
python3 -c 'import searvey.usgs; searvey.usgs.get_usgs_stations()'  # this works
conda deactivate
conda env remove -n "${env_name}"
```

## Conda
```
env_name=test_conda_searvey_0.3.2
mamba create -n "${env_name}" python=3.10 searvey=0.3.2 -y
conda activate "${env_name}"
which python3  
python3 -V
python3 -c 'import searvey.usgs; searvey.usgs.get_usgs_stations()'  # this throws the traceback

# cleanup the environment
conda deactivate
conda env remove -n "${env_name}"
```

**Comment by pmav99** [comment]
OK, this is due to different versions of dataretrieval... PyPI has 1.0.3 while conda-forge has 0.7

I pinged the dataretrieval maintainers here: https://github.com/conda-forge/dataretrieval-feedstock/pull/8

https://anaconda.org/conda-forge/dataretrieval

PS. we probably need to add `dataretrieval >= 1` in the meta.yaml
